spring.application.name=BookSphere

#Connection to the DBS used in the project

# MongoDB: replace with your connection string if you are using the local instance of BookSphere
spring.data.mongodb.uri=mongodb+srv://admin:admin@booksphere.nzqkgkj.mongodb.net/BookSphere?retryWrites=true&w=majority


# Neo4j: I'm using the local instance, change it otherwise
spring.data.neo4j.uri=neo4j://127.0.0.1:7687
spring.data.neo4j.authentication.username=neo4j
spring.data.neo4j.authentication.password=password


management.endpoint.health.show-details=always