spring.data.mongodb.uri=mongodb://10.1.1.77:27018,10.1.1.78:27019,10.1.1.80:27020/booksphere?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=true&w=majority

 #&wtimeoutMS=10000



##properties

spring.neo4j.uri=bolt://10.1.1.78:7687

# Use the credentials you set during the first login
spring.neo4j.authentication.username = neo4j
spring.neo4j.authentication.password = password

# The database name (Community Edition is always 'neo4j')
spring.data.neo4j.database=neo4j