# MongoDB Configuration (WSL)
spring.data.mongodb.uri=mongodb://localhost:27017/booksphere
spring.data.mongodb.database=booksphere

# Neo4j Configuration (WSL) - Using WSL IP address
spring.neo4j.uri=bolt://172.28.78.198:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.neo4j.driver=DEBUG
logging.level.it.unipi.bookSphere=DEBUG